### ISSUE TITLE
Improve TCPSocket buffering

### ISSUE THREAD

**Issue by ioquatix** [socketry/async-io#11]
As outlined in https://github.com/socketry/async-io/pull/10, there are issues with `TCPSocket#gets`, `#puts`, `#read` and `#write`.

**Comment by ioquatix** [comment]
@jjyr Here is something which seems to work, but I think we need more specs to cover the behaviour of `TCPSocket`, and specifically documentation explaining the situation https://github.com/socketry/async-io/pull/10#issuecomment-421762652 so that people generally avoid using `TCPSocket` unless required.

**Comment by jjyr** [comment]
I believe we can reuse some test cases from https://github.com/socketry/lightio/blob/master/spec/lightio/library/io_spec.rb#L179

**Comment by ioquatix** [comment]
That makes sense, in the end, I'm not entirely sure how, say, `#syswrite`, `#sync=`, `#write`, and `#puts` interact with each other. It seems like the only option is to make specs to ensure the behaviour matches up with `::TCPSocket`.

**Comment by jjyr** [comment]
So I think maybe we should keep the IO interface simple, to offer some basic IO operations like: `#write` `#read` `#gets` `#puts` is enough, is hard to maintain compatible in so many related IO operations( for example, how to implement the `readchar` method?). 

By the way, we have no reason to maintain 100% compatible if users should aware the difference between Async::IO and std IO(or shouldn't they?).

**Comment by ioquatix** [comment]
I made some minor compatibility improvements https://github.com/socketry/async-io/commit/de51e2b7a95d7cafcb9e7af25e094635892556d1

**Comment by chuckremes** [comment]
> Longer term, I think I'd like to explore a new model for IO, including using FFI to directly access POSIX sockets/file descriptor methods. This would work better for JRuby too which currently has a very poor implementation of Ruby IO. But I can't really go down this path yet.

I like the sound of that. :)

**Comment by ioquatix** [comment]
I believe these issues are all fixed, that being said the implementation could probably be improved.
