### ISSUE TITLE
Improve Async::IO::TCPSocket compatibility with http.rb

### ISSUE THREAD

**Issue by ThibG** [socketry/async-io#12]
I'm trying to replace puma by falcon in Mastodon, and take advantage of async processing of (outbound) HTTP requests. Since Mastodon uses a lot of http.rb features, I attempted to use http.rb with `Async::IO::TCPSocket` as the class used for sockets.

To do so, I first tried something like:
```ruby
#!/usr/bin/env ruby

require 'http'
require 'async/io'
require 'async/io/tcp_socket'

Async::Reactor.run do
  puts HTTP.public_send('get', 'https://google.fr', { socket_class: Async::IO::TCPSocket })
end
```

which caused an error: `ArgumentError: wrong number of arguments (given 1, expected 0)`
because `Async::IO::Generic#nonblock=` is defined as an alias of `Async::IO::Generic#nonblock` and does not take any argument.

I fixed async-io, but the same example then caused a segfault. I figured this could be because of `http.rb` using an incorrect `SSLSocket` to wrap around `Async::IO::TCPSocket` so I tried the following:

```ruby
#!/usr/bin/env ruby

require 'http'
require 'async/io'
require 'async/io/tcp_socket'
require 'async/io/ssl_socket'

Async::Reactor.run do
  puts HTTP.public_send('get', 'https://google.fr', { socket_class: Async::IO::TCPSocket, ssl_socket_class: Async::IO::SSLSocket })
end
```
… which failed because of ```NoMethodError: undefined method `hostname=' for #<Async::IO::TCPSocket:0x00005628188c4240>```

At that point I'm not too sure how that could be fixed.

**Comment by ThibG** [comment]
After a bit more investigation, it seems that `http.rb` creates a `SSLSocket` instance via `ssl_socket_class.new`, while properly-wrapped `Async::IO::SSLSocket` have to be created by using `Async::IO::SSLSocket.wrap`, so `Async::IO:SSLSocket` cannot be directly used as a drop-in replacement, but a thin wrapper translating `new` to `wrap` seem to do the trick.

**Comment by ioquatix** [comment]
Do you think you can submit a PR including a failing test case? I don't mind including `http.rb` into a test suite, e.g. `http_rb_spec.rb` or something similar.

**Comment by ioquatix** [comment]
I'm not sure which is best solution. I do like implicit wrappers, but I'd prefer to have something a bit less "overloaded".

**Comment by ioquatix** [comment]
I'm happy with the implicit wrapper approach, so I'm going to leave it as is.
