### ISSUE TITLE
Socket leaking if receiving a `Async::TimeoutError` during creation

### ISSUE THREAD

**Issue by ThibG** [socketry/async-io#14]
I'm having a hard time tracking that down, but I'm seeing a lot of leaking file descriptors.
It appears to happen whenever a timeout occurs when creating an `Async::IO::TCPSocket`.

**Comment by ThibG** [comment]
It seems `Async::IO::Socket#connect` is called, and gets interrupted by the timeout, and I'm not sure how to access the socket to close it, since the socket is supposed to be returned by `connect`…

**Comment by ioquatix** [comment]
In theory, the socket should be closed by this logic here:

https://github.com/socketry/async-io/blob/master/lib/async/io/socket.rb#L107-L117

Followed by

https://github.com/socketry/async-io/blob/master/lib/async/io/socket.rb#L140-L146

But it looks like maybe that `rescue` should be changed to `rescue Exception`. Do you think you could submit a failing test case?

**Comment by ThibG** [comment]
Indeed, changing this line to `rescue Exception` catches exceptions that weren't caught before, and it appears to not be leaking sockets anymore!
Not sure how to reliably trigger a connection timeout or check for socket leakage within Ruby, though.

**Comment by ioquatix** [comment]
Thanks for checking that out. Do you want to submit a PR to fix the issue? One way to test it would be to make a mock or subclass where `wrapper.connect` fails by `raise Async::TimeoutError`.
