### ISSUE TITLE
Detecting server disconnection in chat sample

### ISSUE THREAD

**Issue by jeremyjung** [socketry/async-io#20]
Hello! I am looking through the Socketry libraries and getting a better understanding of how to use them.  Thank you for providing examples, they were very helpful.

In the chat example, if the server closes it's connection, the read_line call on the user object immediately receives an EOFError.  However, because it is running in a task, the exception stays in the task and does not make it to the rescue statement.  The application then appears to freeze.  I attempted to address this by moving the read loop into a task and waiting both tasks so that exception handling could occur.  

```ruby
Async::Reactor.run do |task|
  socket = endpoint.connect
  stream = Async::IO::Stream.new(socket)
  user = User.new(stream)
  
  connection = task.async do
    while line = user.read_line
      puts line
    end
  end
  
  read_input = task.async do
    while line = input.read_line
      user.write_lines line
    end
  end

  [connection, read_input].each(&:wait)

rescue EOFError
  # It's okay, we are disconnecting, because stdin has closed.
ensure
  user.close && connection.stop unless [:failed, :stopped].include?(connection.status)
  input.close && read_input.stop unless [:failed, :stopped].include?(read_input.status)
end
```

However, with this approach the following exception occurs once the server connects.

```
 1.94s: <Async::Task:0x3fffea7fd24c failed>
      |  Async::Wrapper::Cancelled: The operation has been cancelled!
      |  → /home/name/.gem/ruby/2.6.1/gems/async-1.15.1/lib/async/task.rb:51 in `yield'
      |    /home/name/.gem/ruby/2.6.1/gems/async-1.15.1/lib/async/wrapper.rb:211 in `wait_for'
      |    /home/name/.gem/ruby/2.6.1/gems/async-1.15.1/lib/async/wrapper.rb:102 in `wait_readable'
      |    /home/name/.gem/ruby/2.6.1/gems/async-io-1.18.2/lib/async/io/generic.rb:145 in `async_send'
      |    /home/name/.gem/ruby/2.6.1/gems/async-io-1.18.2/lib/async/io/generic.rb:47 in `block in wrap_blocking_method'
      |    /home/name/.gem/ruby/2.6.1/gems/async-io-1.18.2/lib/async/io/stream.rb:195 in `fill_read_buffer'
      |    /home/name/.gem/ruby/2.6.1/gems/async-io-1.18.2/lib/async/io/stream.rb:91 in `read_until'
      |    /home/name/.gem/ruby/2.6.1/gems/async-io-1.18.2/lib/async/io/protocol/line.rb:49 in `read_line'
      |    client.rb:31 in `block (2 levels) in <main>'
      |    /home/name/.gem/ruby/2.6.1/gems/async-1.15.1/lib/async/task.rb:199 in `block in make_fiber'
```

Do you have any suggestions on how error handling should be performed in this case?  If I stop the tasks instead of explicitly closing the streams then I do not get an exception but I am not sure if there are any problems with that approach.

Any thoughts would be appreciated.

**Comment by ioquatix** [comment]
Ah yeah, the behaviour changed slightly, let me fix the example.

**Comment by ioquatix** [comment]
Thanks for your feedback, I am happy to hear the examples are useful.

Your idea is good, but it cannot work.

```ruby
# [connection, read_input].each(&:wait)
connection.wait
read_input.wait
```

Because `connection.wait` never returns until `connection` fails, `read_input.wait` is never called, so the failure in that task is never reported.

You need to use `Async::Notification` to send notification from child task to parent task. The parent task waits until either child task fails or exits, and then it continues (i.e. exits).

Let me know if the updated example is clear. Please ask more questions if you need clarifications.

**Comment by jeremyjung** [comment]
This was great, thank you!  I did not know notifications were in the library and this made their use very clear.

If I have any more questions, would you suggest I create a new issue or reply to this one?

**Comment by ioquatix** [comment]
Please make a new issue :)
