### ISSUE TITLE
UNIXEndpoint has to be required

### ISSUE THREAD

**Issue by jcalvert** [socketry/async-io#22]
In order to get UNIX socket functionality you have to `require 'async/io/unix_endpoint'` explicitly. Not sure if this is because UNIX sockets aren't really supported at this time.

**Comment by ioquatix** [comment]
They are fully supported. What problem are you having?

**Comment by jcalvert** [comment]
This is fairly minor but perhaps this is more illustrative:

```
irb(main):001:0> require 'async/io'
=> true
irb(main):002:0> Async::IO::Endpoint.unix('/tmp/foo', Socket::SOCK_SEQPACKET)
NoMethodError: undefined method `unix' for Async::IO::Endpoint:Class
	from (irb):2
	...
irb(main):003:0> require 'async/io/unix_endpoint'
=> true
irb(main):004:0> Async::IO::Endpoint.unix('/tmp/foo', Socket::SOCK_SEQPACKET)
=> #<Async::IO::UNIXEndpoint:0x007f80f795e1b8 @options={}, @address=#<Addrinfo: /tmp/foo SOCK_SEQPACKET>, @path="/tmp/foo">
```

**Comment by ioquatix** [comment]
That is the expected behaviour. What do you propose to change?

**Comment by jcalvert** [comment]
Ah, I would have expected that requiring the gem would actually load all the classes in the gem.

**Comment by ioquatix** [comment]
There are different ideas about how this should work. I normally have something like `async/io` which includes what most users would want by default. But more specific functionality is not included by default to minimise memory usage and load time.
