### ISSUE TITLE
[Question] Need help by giving a UDP example.

### ISSUE THREAD

**Issue by tan-wei** [socketry/async-io#25]
First of all, thanks for this project.

I'm a beginner in Ruby, so I can not quickly learn how to use this library with UDP just from the source code. Could you give us a UDP example, I think it must be easier than TCP example.

Thanks very much!

**Comment by ioquatix** [comment]
Let me know if the example I gave you was good enough.

**Comment by tan-wei** [comment]
> 
> 
> Let me know if the example I gave you was good enough.

Pretty clear, thanks very much! Hope you have a good day.

**Comment by tan-wei** [comment]
I have another naive question about the UDP examples. Is the method `send` or `recvfrom` async operations?

**Comment by ioquatix** [comment]
Both are asynchronous.

**Comment by tan-wei** [comment]
Forgive me, I have an extra question about `async-io`.

It's easy to write a UDP server as the examples shows, after a complete receive from `socket.recvfrom`, `socket.send` is called after:
```ruby
require 'async'
require 'async/io'

endpoint = Async::IO::Endpoint.udp("localhost", 5300)

Async do |task|
	endpoint.bind do |socket|
		while true
			data, address = socket.recvfrom(1024)
			socket.send(data.reverse, 0, address)
		end
	end
end
```

However, when I try to write a UDP endpoint, which can be randomly send data and receive data, `Async::Wrapper::Cancelled` is raised, because the events `send` and `receive` are randomly called, the later event will cancell the former one:
```ruby
require 'async'
require 'async/io'

endpoint = Async::IO::Endpoint.udp("localhost", 5300)

Async do |task|
	endpoint.bind do |socket|
		task.async do
			loop do
				data, address = socket.recvfrom(1024)
				pp data
				pp address
			end
		end

		task.async do
			loop do
				task.sleep rand(1)
				socket.send "Hello World!", 0, Addrinfo.udp("localhost", 5200)
			end
		end
	end
end
```
Obviously, the code is ill-designed. How to write *async* code to fulfill the requirement? Thanks!

**Comment by ioquatix** [comment]
Hmm, getting `Async::Wrapper::Cancelled` is a little bit confusing, I wonder why it's happening. I'll try out your example.

**Comment by ioquatix** [comment]
```ruby
#!/usr/bin/env ruby

require 'async'
require_relative '../lib/async/io'

endpoint = Async::IO::Endpoint.udp("localhost", 5300)

Async do |task|
	endpoint.bind do |socket|
		# This block executes for both IPv4 and IPv6 UDP sockets:
		loop do
			data, address = socket.recvfrom(1024)
			pp data
			pp address
		end
	end
	
	# This will try connecting to all addresses and yield for the first one that successfully connects:
	endpoint.connect do |socket|
		loop do
			task.sleep rand(1..10)
			socket.send "Hello World!", 0
		end
	end
end
```

This works.

**Comment by ioquatix** [comment]
It's failing because you are making a nested async task without waiting on it so the outer scope (bound) is exiting and the socket is closed.

**Comment by tan-wei** [comment]
Got it. I'll try your code. Thanks for your reply.
I didn't know that `endpoint` can be `bind` and `connect` at the same time.

**Comment by ioquatix** [comment]
Endpoint is the abstraction for some kind of underlying address. It's not stateful (in theory).
