### ISSUE TITLE
[Chore] Ruby 2.7.0 changes

### ISSUE THREAD

**Issue by noraj** [socketry/async-io#35]
```
/home/noraj/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/async-io-1.27.1/lib/async/io/host_endpoint.rb:98: warning: The called method `tcp' is defined here
```

Ruby 2.7

- Quick changelog: https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/
- Comprehensive changelog: https://rubyreferences.github.io/rubychanges/2.7.html
- Ruby 2.7 NEWS: Commentary by Cookpad’s Full Time Ruby Committers: https://sourcediving.com/ruby-2-7-news-commentary-by-cookpads-full-time-ruby-comitters-bdbaacb36d0c

I don't know what is causing the warning but it was not there in 2.6.

Related issue https://github.com/picatz/shodanz/issues/32

**Comment by ioquatix** [comment]
https://github.com/socketry/async-http/issues/42 fixed in `async-http` 0.50.0
