### ISSUE TITLE
A reactor with a waiting trap never ends

### ISSUE THREAD

**Issue by bruno-** [socketry/async-io#41]
First off, thank you for the amazing `async` ecosystem.

I'm not sure if this is a real problem (still learning about `async` and other gems) but here's what I'm observing:

```ruby
require "async"
require "async/io/trap"

trap = Async::IO::Trap.new(:INT)
trap.install!

Async do
  trap.async do
    puts "Never ending"
  end
end
```

The above ruby program will never end. My expectation was that it SHOULD end because it should behave equivalently to this "regular" ruby program:

```ruby
Signal.trap(:INT) do
  puts "I do nothing, and then I end"
end
```

Is this even a problem?
Thanks

**Comment by ioquatix** [comment]
Thanks for raising this issue.

We should make the inner async block transient.

Here is an example:

```
require "async"
require "async/io/trap"

trap = Async::IO::Trap.new(:INT)
trap.install!

Async do |parent|
	Async(transient: true) do
		trap.wait do
			puts "Never ending"
		end
	end
end

puts "Done"
```

A transient task will not stop the reactor from exiting.

**Comment by ioquatix** [comment]
```
require "async"
require "async/io/trap"

trap = Async::IO::Trap.new(:INT)
trap.install!

Async do
  trap.async(transient: true) do
    puts "Never ending"
  end
end
```

This example now works as expected. Can you please check it and let me know?

Also, thanks for appreciating my work!

**Comment by bruno-** [comment]
Yes, the examples above now work. Thank you very much 🙏

**Comment by ioquatix** [comment]
You are most welcome!
