### ISSUE TITLE
Will not install with Ruby 3.x

### ISSUE THREAD

**Issue by LeamHall** [socketry/async-io#42]
Getting the following:   async-io requires Ruby version ~> 2.5. The current ruby version is 3.0.0.dev.

**Comment by ioquatix** [comment]
Yes, that is by design, there will be a new release soon.

**Comment by ioquatix** [comment]
Fixed.

**Comment by LeamHall** [comment]
Thanks! Confirmed fixed on ruby 3.0.0dev (2020-09-19T00:07:08Z master 6cb6d5abc3) [x86_64-linux].
