### ISSUE TITLE
surfacing exceptions from an accept block?

### ISSUE THREAD

**Issue by emiltin** [socketry/async-io#44]
If an exception is raised inside an accept block, how can I surface this to the enclosing task?

```ruby
Async do |task|
  # This is a synchronous block within the current task:
  endpoint.accept do |client|
    # This is an asynchronous block within the current reactor:
    raise "boom"
  end
  # how can i know what went wrong in the accept block?
end
```

The comments in the documentation examples (inserted above) seem to indicate that the tasks handling connectings are within the reactor, not the enclosing task. Do I need to use e.g an async queue?

**Comment by ioquatix** [comment]
Because `accept` is a loop, it does not break when one client breaks.

If you want to handle the exception, you need to do it in the child task.

``` ruby
Async do |task|
  # This is a synchronous block within the current task:
  endpoint.accept do |client|
    # This is an asynchronous block within the current reactor:
    raise "boom"
  rescue => error
    # i know what went wrong in the accept block.
  end
end
```

Does this make sense? Can you explain what problem you are trying to solve?

**Comment by emiltin** [comment]
We're using the rmsp gem to test traffic light controller equipment. The rsmp gem is designed to keep the tcp/ip connection to the equipment up, even if processing a particular message fails. Exception are therefore caught in sub tasks and logged, to avoid tasks ending up in a failed state.
But when testing, we need an option to surface all exceptions to the task handling the testing.

When you manually create a sub task, the task is returned to the parent task, where wait() will reraise the exception in the parent task:
```ruby
Async do |task|
  subtask = task.async do
    raise "boom"
  end
  puts subtask.status
  subtask.wait
rescue => error
  puts "subtask went #{error}"
end
```
 
It makes sense that you don't get the child task when using accept, since you don't know when connections will open, so I was wondering how to access the child task from the parent task. But maybe it's better to use a queue to notify the parent task (or the test task) about exceptions in child tasks?

**Comment by ioquatix** [comment]
Do you just need to accept one connection?

**Comment by emiltin** [comment]
No, I need to handle multiple connections. The gem let's you start an rsmp server, which handles network connections and communication. On top of that is some test code which interacts with that server, send commands, waits for responses, etc. If an error occurs in the server during testing (e.g an invalid message is received) I want the currently active test to fail and raise an exception. But the test and the server runs in separate async tasks. 

It seems the following might work. In the test task, start a sentinel child task, which listens for errors queued by the server. If it receives an error, it stores the error and uses Task#stop on the parent test task:
 
```ruby
require 'async'
require 'async/queue'

reactor = Async::Reactor.new
queue = Async::Queue.new
error = nil

# server task, which persist between tests:
reactor.async do |task|
  task.sleep 1 # accept incoming connections and handle communication
  queue.enqueue "boom" # something went wrong, inform listeners
end

# for each test do:
reactor.run do |task| # continue the reactor
  sentinel = task.async do |sentinel| # listen for errors in the server
    error = queue.dequeue
    task.stop
  end
  puts "testing..."
  task.sleep 2 # interact with the server to test equipment
  puts "done"
  sentinel.stop
  reactor.interrupt # interrupt the reactor, so the test framework can move on to the next test
end

raise error if error # if error occured in server during test, reraise outside async task 
```

In this example, the test takes 2 seconds, but is stoped by the sentinel after 1 second, due to an error in the server. The error is then raised outside the async block, so it's seen by the test framework.

**Comment by ioquatix** [comment]
Yes, that looks okay to me.

**Comment by emiltin** [comment]
Sweet, thank you for taking a look.
