### ISSUE TITLE
PR #72 has introduced a minimum Ruby version requirement of v2.7

### ISSUE THREAD

**Issue by fallwith** [socketry/async-io#74]
#72's use of `array[..n]`:

```ruby
return @read_buffer[..([size, @read_buffer.size].min - 1)]
```

won't work with Rubies older than 2.7.

We'll need to either refactor to support Ruby 2.5 and 2.6, or bump the `required_ruby_version` value in `asycn-io.gemspec` accordingly.

**Comment by ioquatix** [comment]
Ah sorry about that. I’ll bump the minimum supported version in the gemspec.

**Comment by ioquatix** [comment]
Okay, it was an easy fix to restore compatibility, so I've done that.

**Comment by ioquatix** [comment]
Sorry, messed up the cross referencing. This was fixed in https://github.com/socketry/async-io/pull/75.
